---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[ca_openldap::server]
    attributes:
      ca_openldap:
        tls:
          enable: "no"
