---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

verifier:
  name: inspec

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[ca_openldap::server]
      - recipe[ca_openldap::schemas]
      - recipe[ca_openldap::dit]
      - recipe[ca_openldap::populate]
      - recipe[ca_openldap::ppolicy]
      - recipe[use_entry_resource]
    attributes:
      ca_openldap:
        general_configuration_options:
          olcAllows: "::delete::"
        populate:
          update_enable: true
        tls:
          enable: "no"
